name: build
on: [ pull_request, push ]

jobs:
  build:
    if: "!startsWith(github.event.head_commit.message, '[skip]')"
    strategy:
      matrix:
        java: [ 21 ]
    runs-on: ubuntu-latest
    steps:

      - name: checkout repository
        uses: actions/checkout@v3

      - name: Get branch name
        id: get_branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Get latest commit hash
        id: get_hash
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: cache gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/loom-cache
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: give gradle execution permissions
        run: chmod +x ./gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: building
        run: ./gradlew build


      - name: upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: biomechanical-artifacts
          path: build/libs/*.jar

      - name: Send building message to discord
        uses: fateyan/action-discord-notifier@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message-title: Building mod from branch ${{ steps.get_branch.outputs.branch }}

      - name: Send built file to discord
        uses: sinshutu/upload-to-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: ./build/libs/*.jar
